- Cargo.toml
- src/lib.rs
This adds the method set_symlink_file_times that doesn't follow
symlinks and instead sets the time of the symlink itself.
Because implementations of set_file_times and set_symlink_file_times
are so similar for both windows and unix I have also refactor the code
be adding set_file_times_w for windows and set_file_times_u for unix
that contains the shared code for the two functions.
> Add set_symlink_file_times for better symlink support

- src/lib.rs
Requires https://github.com/redox-os/redoxfs/pull/33 (which is already merged, but worth noting).
> redox: fix setting times on readonly file

- Cargo.toml
it will permit rustc to pick a filetime version with `utimensat` changes for netbsd, openbsd, and solaris
> bump version to 0.1.13

- src/unix/linux.rs
Even when libc has `utimensat`, the kernel may return `ENOSYS`,
and then we'll need to use the `utimes` fallback instead.
> Add a fallback for utimensat ENOSYS

- src/lib.rs
- src/redox.rs
- src/unix/mod.rs
- src/windows.rs
My primary motivation for this is to be able to handle pre-Unix-epoch timestamps, and having a `from_system_time()` is also useful as I'm currently converting to and from Unix epoch to get from SystemTime to FileTime. 
As was suggested in #6, I've avoided breaking existing API functions by casting between signed and unsigned integers, though this means that nonsense will be returned by the `seconds()`, `seconds_relative_to_1970()` and `nanoseconds()` functions on Unixy systems when FileTime is pre-Unix-epoch. I think breakage would be better as it is a 0.1.x library and to/from Unix timestamp functions should really be able to handle the case where they're pre-Unix-epoch, but I thought I'd make minimal changes and see what you thought.
I'm not sure if the handling of mtime_nsec() values …
> Add function to create FileTime from SystemTime

- src/unix/mod.rs
My primary motivation is to fix #24 
However this also fixes #29, but I didn't test it.
On emscripten `utimes` is just a wrapper on top of `utimensat`, which is why my change makes sense:
https://github.com/kripken/emscripten/blob/6e4b98636618989bcd99308391e51aa1b81f4c61/system/lib/libc/musl/src/linux/utimes.c#L9
https://github.com/kripken/emscripten/blob/6e4b98636618989bcd99308391e51aa1b81f4c61/system/lib/libc/musl/src/stat/futimesat.c#L20
However the tests don't work because:
- It looks like `flags` have to be 0, so `set_symlink_file_times` doesn't work: https://github.com/kripken/emscripten/blob/52ff847187ee30fba48d611e64b5d10e2498fe0f/src/library_syscall.js#L1260
- Emscripten doesn't seem to differentiate between last access time and last modification time. It just uses the highest of …
> Fix Emscripten and FreeBSD

- src/unix/mod.rs
Without this, compilation on OpenBSD causes the following error:
```
error[E0425]: cannot find value `lutimes` in module `libc`
--> src/unix/utimes.rs:12:42
|
12 |     super::utimes(p, atime, mtime, libc::lutimes)
|                                          ^^^^^^^ did you mean `futimes`?
error: aborting due to previous error
```
which means that things like `mdbook` can't build.
> OpenBSD doesn't have lutimes so use utimensat instead.

- README.md
- src/lib.rs
This is a follow up to the iday from https://github.com/rust-lang/cargo/pull/6484#issuecomment-451601874
This adds a `FILETIME_EMULATE_SECOND_ONLY_SYSTEM`, that allows debugging HFS from other hardware.
> debug HFS on other systems

- src/lib.rs
- src/wasm.rs
Provide `unimplemented` functions for wasm32 target. This prevents from crashing when compiling filetime as a dependency of tar-rs. If any of these functions get called though, the program will crash at runtime.
> Do not crash when compiling to wasm

- .travis.yml
- src/lib.rs
- src/unix/macos.rs
- src/unix/mod.rs
This PR enables `utimensat` for MacOS target. It's probably not done in the most ergonomic way possible but I'm happy to work on it until it meets the expectations :-) Anyhow, it fixes problems with MacOS target in CraneStation/wasi-common#54.
cc @marmistrz @alexcrichton
> Enable utimensat for macos target OS

- src/lib.rs
Now, matches the actual version of the crate which is `0.2`.
> Update crate version in docs

- Cargo.toml
- src/lib.rs
The tempdir crate has been deprecated by their author in favor of using
the tempfile crate.
> Migrate tempdir dep to tempfile

- src/unix/utimes.rs
The uClibc library does not provide an implementation for `futimes`, but it does provide `futimens`. This PR fixes the implementation of `set_file_handle_times` for uClibc by substituting in `futimens` and also provides the required `to_timespec` function.
> Adding support for uclibc's funtimens in set_file_handle_times

- src/lib.rs
Useful as the value of atime and/or mtime for files in an LRU cache.
> Add FileTime::now()

- src/unix/mod.rs
As part of the preparation for rust-lang/rust#55553, add support for the Solaris-like illumos target.
> Add illumos target support

- src/unix/mod.rs
The `futimes` call is not available on Haiku.
> Haiku: use the utimensat module

- src/lib.rs
- src/windows.rs
Currently, a `PermissionDenied` error is raised when using `set_file_times`, `set_file_mtime`, `set_file_atime` or `set_symlink_file_times` and passing a path to a folder on Windows.
Passing the [`FILE_FLAG_BACKUP_SEMANTICS`](https://docs.microsoft.com/en-us/windows/win32/fileio/file-security-and-access-rights) flag when opening the file handle fixes the issue.
This PR also adds tests for setting directory times.
> Fix PermissionDenied error with Windows folders

- src/unix/utimensat.rs
`futimens` is not available in Android NDK before version 19:
https://stackoverflow.com/questions/19374749/how-to-work-around-absence-of-futimes-in-android-ndk
The reason is that bionic libc didn't implement this wrapper for
`utimensat`.
`utimensat` syscall was available before that, so it is more compatible.
Fixes #56
> utimensat.rs: remove use of futimens

- src/unix/mod.rs
Noticed that `set_file_mtime()` was generating EINVAL due to incorrect value for UTIME_OMIT. This PR adds a new potential config value for UTIME_OMIT in the same manner done for Mac OS.
> Setting UTIME_OMIT correctly for OpenBSD

- .github/workflows/main.yml
- src/unix/mod.rs
Android variant is a copy of utimensat with a modification to remove
futimens call, so it should follow the pattern used for utimensat module
used for "solaris, illumos, ..." case.
Follow-up for #59 
Fixes #62
> Do not include utimes module on android

- src/unix/mod.rs
I got EINVAL from set_file_mtime() on FreeBSD and fixed it by adding the correct definition for UTIME_OMIT.
Moreover I also tried to find the correct definitions for the other values of target_os.
> Setting UTIME_OMIT correctly for FreeBSD, Haiku and Illumos

- Cargo.toml
- src/redox.rs
This fixes building on new versions of Redox
> Adapt to UTF-8 only paths in redox_syscall 0.2.8

- src/unix/macos.rs
Minor typo fix: futimens / utimensat were added in 10.13, not 10.3.
References:
- https://github.com/Kitware/CMake/commit/96329d5dffdd5a22c5b4428119b5d3762a8857a7
- https://bugs.python.org/issue31601
- https://github.com/ziglang/zig/issues/5023
> Fix typos in macos.rs

- src/unix/android.rs
This gets `cargo test` to pass on Android (previously it failed on the two symlink tests).
> fix Android symlink flag

- Cargo.toml
The Android fix is currently on the list of things blocking Android support at https://github.com/uutils/coreutils/pull/3396.
> Bump to 0.2.16

- Cargo.toml
- src/windows.rs
This PR migrates remove-dir-all from winapi to windows-sys.
Windows-sys is actively maintained, by Microsoft, and has recently
started to be adopted in the ecosystem; mio, parking_lot, wasmtime,
and others have moved to windows-sys.
> Migrate from winapi to windows-sys.

- src/unix/mod.rs
We are porting rust on AIX, see https://github.com/rust-lang/compiler-team/issues/553.
`utimensat` routines are added in https://github.com/rust-lang/libc/pull/2894/files#diff-cdca763d7494a8b247c48e3d317bd4dfbd7c2792f4363fa5070805958650b44aR1989 and https://github.com/rust-lang/libc/pull/2894/files#diff-cdca763d7494a8b247c48e3d317bd4dfbd7c2792f4363fa5070805958650b44aR1878
> Add support for AIX

- src/unix/utimensat.rs
IIUC, we are setting the timestamp of the symlink file rather than the target file. So the flag should be `true` as linux.
> Correct the timestamp of symlink if using `utimensat`

- src/unix/linux.rs
- src/unix/mod.rs
In a future release of the `libc` crate, `libc::timespec` will contain private padding fields on `*-linux-musl` targets and so the struct will no longer be able to be created using the literal initialization syntax.
Update struct literal use of `libc::timespec` to initialize to zero first and then manually update the appropriate fields. Also updates a raw syscall to use the libc function instead as on musl 1.2, it correctly handles `libc::timespec` values which, in musl 1.2, are always 16 bytes in length regardless of platform.
See also https://github.com/rust-lang/libc/pull/2088
> Update use of libc::timespec to prepare for future libc version

- Cargo.toml
- src/redox.rs
Libredox is the new recommended Redox API (the other one being `libc`) , now that Redox no longer guarantees its syscall ABI to be stable.
> Replace redox_syscall with libredox.

- src/redox.rs
The type is c_long on some platforms and i64 on others.
> redox: relax type requirement for tv_nsec, fixing x86 32-bit
